name       : mate-menu
version    : 19.04.0
release    : 6
source     :
    - https://github.com/ubuntu-mate/mate-menu/archive/19.04.0.tar.gz : dbcf2af2c12fbbf4a9014aecd42f46ff159ff94a2d1efc0603abc5431a06a3aa
license    :
    - GPL-2.0-or-later
    - MIT
component  : desktop.mate
summary    : Advanced menu for MATE Desktop
description: |
    An advanced menu for MATE. Supports filtering, favorites,
    auto-session, and many other features. This menu is a fork
    of MintMenu.
builddeps  :
    - python-distutils-extra
rundeps    :
    - mate-menus
    - mate-panel
    - python-configobj
    - python-setproctitle
    - python-unidecode
    - python-xlib
    - pyxdg
    - xdg-utils
setup      : |
    %python3_setup
install    : |
    %python3_install
