name       : mate-menu
version    : 18.04.3
release    : 5
source     :
    - https://github.com/ubuntu-mate/mate-menu/archive/18.04.3.tar.gz : 8fe0ccbc667ca7f6cb1cd6a7d86961e755ce53e7360e6e59a45a4eeae13b1331
license    :
    - GPL-2.0-or-later
    - MIT
component  : desktop.mate
summary    : Advanced menu for MATE Desktop
description: |
    An advanced menu for MATE. Supports filtering, favorites,
    auto-session, and many other features. This menu is a fork
    of MintMenu.
builddeps  :
    - python-distutils-extra
    - python-setuptools
rundeps    :
    - mate-panel
    - python-configobj
    - python-setproctitle
    - python-xlib
    - pyxdg
    - xdg-utils
setup      : |
    %python_setup
install    : |
    %python_install
