name       : mate-menu
version    : 17.04.2
release    : 2
source     :
    - https://bitbucket.org/ubuntu-mate/mate-menu/get/17.04.2.tar.gz : e374fd210e9c222fdc04837505b77505f9e778c87b44119f5b110f3b94e25059
license    : GPL-2.0
component  : desktop.mate
summary    : Advanced menu for MATE Panel, a fork of MintMenu
description: |
    Advanced menu for MATE Panel, a fork of MintMenu
builddeps  :
    - python-distutils-extra
    - python-setuptools
rundeps    :
    - mate-panel
    - python-configobj
    - pyxdg
    - python-xlib
    - xdg-utils
setup      : |
    %python_setup
install    : |
    %python_install
