name       : mate-menu
version    : 22.04.1
release    : 12
source     :
    - https://github.com/ubuntu-mate/mate-menu/archive/refs/tags/22.04.1.tar.gz : bccb5e624ed031bfdbfcee6d7b7bc23173bdb099830c755b32dd4d1806ea8cba
license    :
    - GPL-2.0-or-later
    - MIT
component  : desktop.mate
summary    : Advanced menu for MATE Desktop
description: |
    An advanced menu for MATE. Supports filtering, favorites, auto-session, and many other features. This menu is a fork of MintMenu.
builddeps  :
    - python-distutils-extra
rundeps    :
    - mate-menus
    - mate-panel
    - python-configobj
    - python-setproctitle
    - python-unidecode
    - python-xlib
    - pyxdg
    - xdg-utils
setup      : |
    %python3_setup
install    : |
    %python3_install
