name       : mate-menu
version    : 16.10.1
release    : 1
source     :
    - https://bitbucket.org/ubuntu-mate/mate-menu/get/16.10.1.tar.gz : ed414ecb9bdf3fa4fea7b4e08c3881f7cde046571878637c6ec169f1083aabc8
license    : GPL-2.0
component  : desktop.mate
summary    : Advanced menu for MATE Panel, a fork of MintMenu
description: |
    Advanced menu for MATE Panel, a fork of MintMenu
builddeps  :
    - python-distutils-extra
    - python-setuptools
rundeps    :
    - mate-panel
    - python-configobj
    - pyxdg
    - python-xlib
    - xdg-utils
setup      : |
    %python_setup
install    : |
    %python_install
