name       : mate-menu
version    : 18.04.0
release    : 4
source     :
    - https://github.com/ubuntu-mate/mate-menu/archive/18.04.0.tar.gz : 4bd15cf628f5cf2d2678b8a0a181e3fe475e5f4dd74859552209807326cf3f4b
license    :
    - GPL-2.0
    - MIT
component  : desktop.mate
summary    : Advanced menu for MATE Desktop
description: |
    An advanced menu for MATE. Supports filtering, favorites,
    auto-session, and many other features. This menu is a fork
    of MintMenu.
builddeps  :
    - python-distutils-extra
    - python-setuptools
rundeps    :
    - mate-panel
    - python-configobj
    - python-setproctitle
    - python-xlib
    - pyxdg
    - xdg-utils
setup      : |
    %python_setup
install    : |
    %python_install
