name       : mate-menu
version    : 22.04.0
release    : 11
source     :
    - https://github.com/ubuntu-mate/mate-menu/archive/refs/tags/22.04.0.tar.gz : 6d3992297c2d34e8897daf2f5a19c4a2862cd623c9f0d1daddc282ceb17bdbbe
license    :
    - GPL-2.0-or-later
    - MIT
component  : desktop.mate
summary    : Advanced menu for MATE Desktop
description: |
    An advanced menu for MATE. Supports filtering, favorites, auto-session, and many other features. This menu is a fork of MintMenu.
builddeps  :
    - python-distutils-extra
rundeps    :
    - mate-menus
    - mate-panel
    - python-configobj
    - python-setproctitle
    - python-unidecode
    - python-xlib
    - pyxdg
    - xdg-utils
setup      : |
    %python3_setup
install    : |
    %python3_install
